/**
 * Email abstraction primitive — core type definitions.
 *
 * These types define the public-facing transactional email surface available
 * to plugins, route handlers, and TSX pages via `email.send()`.
 * Distinct from the admin-only `SmtpNotificationConfig` used for form submission
 * notifications.
 */

/** A message to send via any EmailProvider. */
export interface EmailMessage {
  /** Recipient address or array of addresses. */
  to: string | string[];
  /** Email subject line. */
  subject: string;
  /** HTML email body. */
  html: string;
  /**
   * Plain-text fallback body.
   * When omitted, a plain-text version is auto-generated by stripping HTML tags
   * from the `html` field.
   */
  text?: string;
  /**
   * From address for this message.
   * Overrides the global default from address configured on the provider.
   */
  from?: string;
  /** Reply-To address. */
  replyTo?: string;
}

/** Pluggable email delivery backend. */
export interface EmailProvider {
  send(message: EmailMessage): Promise<void>;
}

/** A named email template that can render itself given data. */
export interface EmailTemplate {
  /** Template name, without file extension (e.g. "welcome"). */
  name: string;
  render(data: Record<string, unknown>): Promise<{ html: string; subject: string; text?: string }>;
}
