/**
 * dune deploy:init <target> — Scaffold deployment configuration.
 *
 * Generates deployment config files for the target platform:
 *
 *   dune deploy:init fly         — fly.toml + Dockerfile for Fly.io
 *   dune deploy:init docker      — Dockerfile + docker-compose.yml
 *   dune deploy:init deno-deploy — Minimal Deno Deploy entry point notes
 *
 * Usage:
 *   dune deploy:init fly [--port <n>] [--app <name>] [--region <code>]
 */

import { join, resolve } from "@std/path";
import { createStorage } from "../storage/mod.ts";
import { loadConfig } from "../config/mod.ts";

export interface DeployInitOptions {
  debug?: boolean;
  port?: number;
  appName?: string;
  region?: string;
  /** Output directory (default: site root) */
  out?: string;
}

// ── Templates ────────────────────────────────────────────────────────────────

const FLY_TOML = (appName: string, port: number, region: string) => `# fly.toml — Fly.io deployment configuration for Dune CMS
# Generated by: dune deploy:init fly
# Docs: https://fly.io/docs/reference/configuration/

app = "${appName}"
primary_region = "${region}"

[build]

[env]
  PORT = "${port}"
  DUNE_ENV = "production"

[http_service]
  internal_port = ${port}
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health/live"
  timeout = "5s"

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  path = "/health/ready"
  timeout = "10s"

[mounts]
  source = "${appName}_data"
  destination = "/data"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
`;

const DOCKERFILE = (port: number) => `# Dockerfile — Dune CMS production image
# Generated by: dune deploy:init fly
#
# Multi-stage build:
#   1. deps — cache JSR/npm dependencies
#   2. app  — minimal runtime image

FROM denoland/deno:latest AS app

WORKDIR /app

# Cache deno.json imports (layer caching)
COPY deno.json deno.lock* ./
RUN deno install --allow-scripts

# Copy application source
COPY . .

# Pre-compile for faster cold starts
RUN deno cache main.ts

EXPOSE ${port}

# Mount content, data, and runtime dirs from the volume
VOLUME ["/data"]

ENV PORT=${port}
ENV DUNE_ENV=production

CMD ["deno", "run", "-A", "main.ts", "serve"]
`;

const DOCKERCOMPOSE = (appName: string, port: number) => `# docker-compose.yml — Local development with Docker
# Generated by: dune deploy:init docker
#
# Usage:
#   docker compose up          # start the site
#   docker compose up --build  # rebuild after code changes

version: "3.9"

services:
  web:
    build: .
    ports:
      - "${port}:${port}"
    environment:
      PORT: "${port}"
      DUNE_ENV: "production"
    volumes:
      # Persist content and admin data
      - ${appName}_data:/data
      # Mount content dir for live editing (remove for production)
      - ./content:/app/content
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${port}/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  ${appName}_data:
`;

const DENO_DEPLOY_NOTES = `# Deno Deploy — Notes for deploying Dune CMS
# Generated by: dune deploy:init deno-deploy
#
# ⚠️  Deno Deploy is for STATIC ASSETS and serverless functions.
# Dune CMS uses the local filesystem for content storage, which is
# NOT available in Deno Deploy's V8 isolate environment.
#
# For full-stack Dune CMS hosting, use one of:
#   - Fly.io (recommended): dune deploy:init fly
#   - Docker: dune deploy:init docker
#   - Any VPS with Deno installed: dune serve
#
# If you want to use Deno Deploy, consider:
#   1. Generate a static site: dune build --static
#   2. Deploy the static output to Deno Deploy or Cloudflare Pages
#   3. Use dune build --static --hybrid for SSG + API routes
#
# Static generation: dune build --static --out=dist --base-url=https://your-site.com
`;

const GITIGNORE_ADDITIONS = `
# Dune runtime (not source files — don't commit these)
.dune/
dist/
`;

// ── Commands ─────────────────────────────────────────────────────────────────

export async function deployInitCommand(
  root: string,
  target: string,
  options: DeployInitOptions = {},
): Promise<void> {
  root = resolve(root);
  const outDir = options.out ? resolve(options.out) : root;

  // Read site config for default values
  const storage = createStorage({ rootDir: root });
  let siteTitle = "my-dune-site";
  try {
    const config = await loadConfig({ storage, rootDir: root, skipConfigTs: true });
    siteTitle = config.site.title
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/^-+|-+$/g, "");
  } catch {
    // Ignore config load failures — use default
  }

  const port = options.port ?? 3000;
  const appName = options.appName ?? siteTitle;
  const region = options.region ?? "iad"; // IAD = Ashburn VA (Fly.io default)

  switch (target) {
    case "fly":
      await initFly(outDir, appName, port, region);
      break;
    case "docker":
      await initDocker(outDir, appName, port);
      break;
    case "deno-deploy":
      await initDenoDeploy(outDir);
      break;
    default:
      console.error(`  ✗ Unknown target: "${target}"`);
      console.error(`    Supported: fly, docker, deno-deploy`);
      Deno.exit(1);
  }

  // Append to .gitignore if needed
  await ensureGitignore(outDir);
}

async function initFly(dir: string, appName: string, port: number, region: string) {
  console.log(`🏜️  Dune — generating Fly.io deployment config...\n`);

  const flyTomlPath = join(dir, "fly.toml");
  const dockerfilePath = join(dir, "Dockerfile");

  let wrote = false;
  if (!await fileExists(flyTomlPath)) {
    await Deno.writeTextFile(flyTomlPath, FLY_TOML(appName, port, region));
    console.log(`  ✅ fly.toml`);
    wrote = true;
  } else {
    console.log(`  ⚠️  fly.toml already exists — skipping`);
  }

  if (!await fileExists(dockerfilePath)) {
    await Deno.writeTextFile(dockerfilePath, DOCKERFILE(port));
    console.log(`  ✅ Dockerfile`);
    wrote = true;
  } else {
    console.log(`  ⚠️  Dockerfile already exists — skipping`);
  }

  if (wrote) {
    console.log(`
  Next steps:
    1. Install flyctl: https://fly.io/docs/hands-on/install-flyctl/
    2. fly auth login
    3. fly apps create ${appName}
    4. fly volumes create ${appName}_data --region ${region} --size 1
    5. fly deploy

  Health probes:
    Liveness:  GET /health/live  (always 200 while running)
    Readiness: GET /health/ready (200 once content index is ready)
`);
  }
}

async function initDocker(dir: string, appName: string, port: number) {
  console.log(`🏜️  Dune — generating Docker deployment config...\n`);

  const dockerfilePath = join(dir, "Dockerfile");
  const composePath = join(dir, "docker-compose.yml");

  if (!await fileExists(dockerfilePath)) {
    await Deno.writeTextFile(dockerfilePath, DOCKERFILE(port));
    console.log(`  ✅ Dockerfile`);
  } else {
    console.log(`  ⚠️  Dockerfile already exists — skipping`);
  }

  if (!await fileExists(composePath)) {
    await Deno.writeTextFile(composePath, DOCKERCOMPOSE(appName, port));
    console.log(`  ✅ docker-compose.yml`);
  } else {
    console.log(`  ⚠️  docker-compose.yml already exists — skipping`);
  }

  console.log(`
  Next steps:
    docker compose up --build

  Or build and run without Compose:
    docker build -t ${appName} .
    docker run -p ${port}:${port} ${appName}
`);
}

async function initDenoDeploy(dir: string) {
  console.log(`🏜️  Dune — Deno Deploy notes...\n`);
  const notesPath = join(dir, "DENO_DEPLOY.md");
  if (!await fileExists(notesPath)) {
    await Deno.writeTextFile(notesPath, DENO_DEPLOY_NOTES);
    console.log(`  ✅ DENO_DEPLOY.md — read this before deploying`);
  } else {
    console.log(`  ⚠️  DENO_DEPLOY.md already exists`);
  }
}

async function ensureGitignore(dir: string) {
  const gitignorePath = join(dir, ".gitignore");
  let existing = "";
  try {
    existing = await Deno.readTextFile(gitignorePath);
  } catch {
    // No .gitignore yet
  }

  const needed = GITIGNORE_ADDITIONS.trim().split("\n").filter((line) => {
    const trimmed = line.trim();
    return trimmed && !trimmed.startsWith("#") && !existing.includes(trimmed);
  });

  if (needed.length > 0) {
    await Deno.writeTextFile(
      gitignorePath,
      `${existing}${existing.endsWith("\n") ? "" : "\n"}${GITIGNORE_ADDITIONS}\n`,
    );
    console.log(`  ✅ .gitignore — added Dune runtime paths`);
  }
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await Deno.stat(path);
    return true;
  } catch {
    return false;
  }
}
