/**
 * Materialize remote island specifiers as local wrapper modules.
 *
 * Fresh's build cache (`MemoryBuildCache.flush`) passes every island
 * specifier that does not start with `file://` through `toFileUrl()`, which
 * throws on `https://`, `jsr:`, and `npm:` specifiers. Islands must
 * therefore reach the Builder as local file paths — but when Dune (or a
 * plugin) runs from JSR, its islands only exist as remote URLs.
 *
 * The bridge: write a tiny wrapper module under
 * `{root}/.dune/remote-islands/` that re-exports the remote module, and
 * register the wrapper's local path instead. esbuild follows the remote
 * import through the Deno esbuild plugin when bundling the browser chunk,
 * and the server-side `import()` of the wrapper resolves to the same module
 * instance as the admin routes' own imports (same URL), so island identity
 * in Fresh's registry is preserved.
 *
 * Local file paths pass through untouched. The wrapper directory is
 * recreated on every boot so stale wrappers from a previous Dune version
 * can't linger.
 */

import { join } from "@std/path";

const REMOTE_PREFIXES = ["https://", "http://", "jsr:", "npm:"];

/** True when `spec` is a remote module specifier rather than a local path. */
export function isRemoteIslandSpec(spec: string): boolean {
  return REMOTE_PREFIXES.some((p) => spec.startsWith(p));
}

/**
 * Replace remote island specifiers with local wrapper module paths.
 * Local paths are returned unchanged, in order.
 */
export async function materializeRemoteIslands(
  specs: string[],
  root: string,
): Promise<string[]> {
  const outDir = join(root, ".dune", "remote-islands");
  let dirReady = false;
  const seen = new Map<string, number>();
  const result: string[] = [];

  for (const spec of specs) {
    if (!isRemoteIslandSpec(spec)) {
      result.push(spec);
      continue;
    }

    if (!dirReady) {
      await Deno.remove(outDir, { recursive: true }).catch(() => {});
      await Deno.mkdir(outDir, { recursive: true });
      dirReady = true;
    }

    const base = (spec.split("/").pop() ?? "island")
      .replace(/\.(tsx|jsx|ts|js|mjs)$/, "")
      .replace(/[^A-Za-z0-9_-]/g, "_") || "island";
    const count = seen.get(base) ?? 0;
    seen.set(base, count + 1);
    const fileName = count === 0 ? `${base}.ts` : `${base}_${count}.ts`;
    const wrapperPath = join(outDir, fileName);

    // `export *` never forwards the default export, so forward it
    // explicitly. Property access (rather than `export { default } from`)
    // keeps the wrapper valid for remote modules without a default export —
    // IslandPreparer skips non-function exports.
    const code = "// Generated by Dune at startup — do not edit.\n" +
      `import * as $mod from ${JSON.stringify(spec)};\n` +
      `export * from ${JSON.stringify(spec)};\n` +
      "// deno-lint-ignore no-explicit-any\n" +
      "export default ($mod as any).default;\n";
    await Deno.writeTextFile(wrapperPath, code);
    result.push(wrapperPath);
  }

  return result;
}
